name: Build Kernel

on:
  push:
    branches: [ "surya" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: namespace-profile-kernel

    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/tc/
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}
           
      - name: Install Package
        run: |
         sudo apt-get install -y libdebuginfod-dev bc zip
         
      - name: Setup timezone
        uses: szenius/set-timezone@master
        with:
          timezoneLinux: "Asia/Bangkok"
      
      - name: Run build script
        run: |
          source build.sh
          echo "ZIPNAME=${ZIPNAME}" >> $GITHUB_ENV

      - name: Setup build date
        run: echo "BUILD_DATE=$(date '+%H:%M %d/%m/%Y')" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@main
        with:
          name: my-artifact
          path: ${{ env.ZIPNAME }}
